---
#
# Setup Browbeat collectd on the Undercloud
#

- name: Install Undercloud collectd Block
  block:
    - name: Generate hosts and ssh-config on Undercloud for Browbeat (Pre-Deployment)
      shell: |
        cd /home/stack/browbeat/ansible
        . /home/stack/stackrc
        /home/stack/browbeat/ansible/generate_tripleo_hostfile.sh -l

    - name: Deploy collectd on Undercloud
      shell: |
        set -o pipefail
        cd /home/stack/browbeat/ansible
        { time ansible-playbook -i hosts install/collectd-openstack.yml --tag undercloud 2>&1 | tee -a {{log_dir}}/011-0-collectd-undercloud-install.log ; } 2>> {{log_dir}}/011-0-collectd-undercloud-install.log
  always:
    - name: Collect Install Undercloud collectd Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/mccloud-log"
        mode: pull
      when: collect_artifacts
