---
#
# Perform Introspection of Overcloud Nodes
#

- name: Introspection Block
  block:
    - name: Run Bulk introspection
      shell:  |
        set -o pipefail
        . /home/stack/stackrc
        { time timeout {{bulk_introspection_timeout}} openstack overcloud node introspect --all-manageable --provide 2>&1 | tee -a {{log_dir}}/007-bulk-introspection.log ; } 2>> {{log_dir}}/007-bulk-introspection.log
      when:
        - bulk_introspection

    - name: Run introspection with retry script
      shell: |
        set -o pipefail
        { time bash /home/stack/introspect.sh 2>&1 | tee -a {{log_dir}}/007-introspection-script.log ; } 2>> {{log_dir}}/007-introspection-script.log
      when: not bulk_introspection

    - name: Generate node-data
      shell: |
        . /home/stack/stackrc
        mkdir ~/node-data
        for i in `ironic node-list | grep avail | awk '{print $2}'`; do openstack baremetal introspection data save $i > node-data/$i; done
  rescue:
     # Collect additional items to sweep into deployment-log for debugging in event of failure
    - name: Collect OpenStack Ironic log files
      become: true
      shell: |
        mkdir -p {{log_dir}}/ironic
        cp -r /var/log/ironic/* {{log_dir}}/ironic

    - name: Dump baremetal node list
      shell:  |
        set -o pipefail
        . /home/stack/stackrc
        openstack baremetal node list 2>&1 | tee -a {{log_dir}}/node-list.log
        openstack baremetal node list | grep None | awk '{print $2}' | xargs -I % openstack baremetal node show % 2>&1 | tee -a {{log_dir}}/node-show.log

    - name: Ensure playbook stops under this condition
      fail:
        msg: "Introspection failures."
  always:
    - name: Collect Introspection Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/deployment-log"
        mode: pull
      when: collect_artifacts
