---
#
# Imports and Configures Nodes
#

- name: Get instackenv.json
  get_url:
    url: "{{instackenv_json}}"
    dest: /home/stack/instackenv.json
    owner: stack
    group: stack

- name: Newton(10)/Ocata(11)/Pike(12) Check if credentials in instackenv.json are correct
  shell: openstack baremetal instackenv validate  -f  /home/stack/instackenv.json
  register: node_status
  failed_when: "'SUCCESS' not in node_status.stdout"
  when: version < 13

- name: Queens(13) Import instackenv.json
  shell: |
    . /home/stack/stackrc
    { time openstack overcloud node import /home/stack/instackenv.json 2>&1 | tee -a /home/stack/log/003-import-instackenv.log ; } 2>> /home/stack/log/003-import-instackenv.log
  when: version >= 13

- name: Newton(10)/Ocata(11)/Pike(12) Import instackenv.json
  shell: |
    . /home/stack/stackrc
    { time openstack baremetal import --json /home/stack/instackenv.json 2>&1 | tee -a /home/stack/log/003-import-instackenv.log ; } 2>> /home/stack/log/003-import-instackenv.log
  when: version < 13

- name: Queens(13) Configure boot
  shell: |
    . /home/stack/stackrc
    { time openstack overcloud node configure --all-manageable 2>&1 | tee -a /home/stack/log/004-configure-boot.log ; } 2>> /home/stack/log/004-configure-boot.log
  when: version >= 13

- name: Newton(10)/Ocata(11)/Pike(12) Configure boot
  shell: |
    . /home/stack/stackrc
    { time openstack baremetal configure boot 2>&1 | tee -a /home/stack/log/004-configure-boot.log ; } 2>> /home/stack/log/004-configure-boot.log
  when: version < 13
