---
#
# Imports and Configures Nodes
#

- name: Validate instackenv.json Block
  block:
    - name: Run validate-instackenv.py
      shell: |
        set -o pipefail
        cd /home/stack/
        { time python validate-instackenv.py -i /home/stack/instackenv.json -o /home/stack/instackenv.valid.json -f /home/stack/invalid-nodes.yaml -u {{inventory_hostname_short}} 2>&1 | tee -a {{log_dir}}/003-validate-instackenv.log ; } 2>> {{log_dir}}/003-validate-instackenv.log
  rescue:
    - name: Collect validate-instackenv.py items
      become: true
      shell: |
        cp /home/stack/instackenv.json {{log_dir}}/instackenv.json
        cp /home/stack/instackenv.valid.json {{log_dir}}/instackenv.valid.json
        cp /home/stack/invalid-nodes.yaml {{log_dir}}/invalid-nodes.yaml
      ignore_errors: true

    # If we don't tolerate node failures, then fail here
    - name: Check if failed nodes tolerated
      fail:
        msg: "Failed nodes and node_failure_tolerance is false"
      when:
        - not node_failure_tolerance

    - name: Count failed nodes
      shell: cat /home/stack/failed-nodes.yaml | wc -l
      register: failed_node_count

    # If we tolerate node failures, then check if we failed too many
    - name: Check Failed Node Count
      fail:
        msg: "Too many failed nodes"
      when:
        - node_failure_tolerance
        - failed_node_count.stdout|int > node_failure_tolerance_count
  always:
    - name: Collect validate instackenv.json Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/deployment-log"
        mode: pull
      when: collect_artifacts

- name: Import/Configure Nodes Block
  block:
    - name: Import instackenv.json
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud node import /home/stack/instackenv.valid.json 2>&1 | tee -a {{log_dir}}/004-import-instackenv.log ; } 2>> {{log_dir}}/004-import-instackenv.log

    - name: Configure boot
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud node configure --all-manageable 2>&1 | tee -a {{log_dir}}/005-configure-boot.log ; } 2>> {{log_dir}}/005-configure-boot.log
      when: version >= 13

    - name: Set Nodes to provide
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud node provide --all-manageable 2>&1 | tee -a {{log_dir}}/006-overcloud-node-provide.log ; } 2>> {{log_dir}}/006-overcloud-node-provide.log
      when:
        - not introspection_enabled
  always:
    - name: Collect Import/Configure Nodes Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/deployment-log"
        mode: pull
      when: collect_artifacts
