---
#
# Imports and Configures Nodes
#

- name: Import/Configure Nodes Block
  block:
    - name: Newton(10)/Ocata(11)/Pike(12) Check if credentials in instackenv.json are correct
      shell: |
        openstack baremetal instackenv validate  -f  /home/stack/instackenv.json
      register: node_status
      failed_when: "'SUCCESS' not in node_status.stdout"
      when: version < 13

    - name: Import instackenv.json
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud node import /home/stack/instackenv.json 2>&1 | tee -a {{log_dir}}/004-import-instackenv.log ; } 2>> {{log_dir}}/004-import-instackenv.log

    - name: Configure boot
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud node configure --all-manageable 2>&1 | tee -a {{log_dir}}/005-configure-boot.log ; } 2>> {{log_dir}}/005-configure-boot.log
      when: version >= 13

    - name: Set Nodes to provide
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time openstack overcloud node provide --all-manageable 2>&1 | tee -a {{log_dir}}/006-overcloud-node-provide.log ; } 2>> {{log_dir}}/006-overcloud-node-provide.log
      when:
        - not introspection_enabled
  always:
    - name: Collect Import/Configure Nodes Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/deployment-log"
        mode: pull
      when: collect_artifacts
