---
#
# Run Browbeat Playbook
#

- hosts: undercloud
  gather_facts: false
  vars_files:
    - vars/data.yaml
    - vars/main.yaml
    - vars/main.local.yaml
  remote_user: stack
  pre_tasks:
    - name: Get timestamp
      command: "date -u +%Y%m%d-%H%M%S"
      delegate_to: localhost
      register: current_ts
    # Creates remote log directory
    - name: Set log directory
      set_fact:
        log_dir: /home/stack/mccloud/log/{{current_ts.stdout}}
    - name: Make sure {{log_dir}} exists
      file:
        path: "{{log_dir}}"
        state: directory
        owner: stack
        group: stack
    # Local artifact directory
    - name: Set Artifact Directory
      set_fact:
        artifact_dir: artifacts/{{version}}-deploy{{deploy_scenario}}-{{current_ts.stdout}}
    - name: Ensure artifact directory exists
      file:
        path: "{{artifact_dir}}"
        state: directory
      delegate_to: localhost
  roles:
    - role: 100-browbeat-run
      when:
        - deploy_browbeat
        - browbeat_run
