---
#
# Deploy playbook for baremetal Undercloud
#

# Wait for Undercloud to be provisioned via Beaker/Foreman
- hosts: undercloud
  gather_facts: false
  remote_user: root
  vars:
    wait_for_ready: true
  tasks:
    # 30 minute timeout (Incase large machine or foreman rebuild is longer than usual)
    - name: Wait for Machine Ready (Incase machine is rebuilding)
      local_action:
        module: wait_for
        host: "{{inventory_hostname}}"
        port: 22
        delay: 15
        timeout: 1800
      when: wait_for_ready
    # Depending on hardware rebuild, we may not have the ssh key exchanged
    - name: Setup | authorized key upload
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    # Pre-deployment tooling may lay down vlans to test network before hand
    # Lets remove this to avoid confusion when debugging or vlan conflicts
    - name: Clean Validation vlans
      become: true
      shell: |
        for interface in $(ip -o link show | awk '{print $2}' | grep "@"  | awk '{split($0,interface,"@"); print interface[1]}')
        do
          ifdown ${interface}
          rm /etc/sysconfig/network-scripts/ifcfg-${interface}
        done

# Tasks as root
- hosts: undercloud
  gather_facts: true
  vars_files:
    - vars/data.yaml
    - vars/main.yaml
    - vars/main.local.yaml
  remote_user: root
  pre_tasks:
    - name: Get timestamp
      command: "date -u +%Y%m%d-%H%M%S"
      delegate_to: localhost
      register: current_ts
    # Defines remote log directory
    - name: Set log directory
      set_fact:
        log_dir: /home/stack/mccloud/log/{{current_ts.stdout}}
    # Local artifact directory
    - name: Set Artifact Directory
      set_fact:
        artifact_dir: artifacts/{{version}}-deploy{{deploy_scenario}}-{{current_ts.stdout}}
    - name: Ensure artifact directory exists
      file:
        path: "{{artifact_dir}}"
        state: directory
      delegate_to: localhost
  roles:
    - role: 000-undercloud-repos
    - role: 001-undercloud-terminal-multiplexers
    - role: 002-undercloud-update-reboot
    - role: 003-undercloud-setup-stack-user
    - role: 004-undercloud-install-tripleo
    - role: 005-undercloud-setup-hostname
    - role: 006-undercloud-private-external-vlan

# Tasks as stack user
- hosts: undercloud
  gather_facts: false
  vars_files:
    - vars/data.yaml
    - vars/main.yaml
    - vars/main.local.yaml
  remote_user: stack
  roles:
    - role: 007-undercloud-install
    - role: 008-undercloud-setup-dns
    - role: 009-undercloud-templates-files
    - role: 010-browbeat-setup
      when: deploy_browbeat
    - role: 011-browbeat-deploy-undercloud-collectd
      when:
        - deploy_browbeat
        - deploy_undercloud_collectd
    - role: 012-undercloud-import-nodes
    - role: 013-undercloud-introspect-overcloud-nodes
      when: introspection_enabled
    - role: 014-undercloud-setup-container-registry
      when: version >= 12
    - role: 015-undercloud-deploy-workarounds

# Overcloud Ready for Deployment now:
    - role: 016-overcloud-deploy
      when: deploy_overcloud
      is_redeploy: false
    - role: 017-browbeat-generate-overcloud-hosts
      when: deploy_browbeat
    - role: 018-browbeat-deploy-overcloud-collectd
      when:
        - deploy_browbeat
        - deploy_overcloud_collectd
    - role: 019-overcloud-disable-admin-quota
      when: disable_quota
    - role: 020-overcloud-create-keypair
      when: create_keypair
    - role: 021-overcloud-create-flavors
      when: create_flavors
    - role: 022-overcloud-upload-images
      when: upload_guest_images
    - role: 023-overcloud-create-security-group
      when: create_security_group
    - role: 024-overcloud-create-networks
      when: create_networks
    - role: 025-undercloud-route-external-traffic
      when: route_external_traffic_from_undercloud
    - role: 026-browbeat-workload-guests-config
      when:
        - create_networks
        - deploy_browbeat
        - browbeat_workload_guests
    - role: 027-browbeat-install
      when: deploy_browbeat
    - role: 028-browbeat-deploy-grafana-dashboards
      when:
        - deploy_browbeat
        - deploy_grafana_dashboards
    - role: 029-browbeat-shaker-image-build
      when:
        - deploy_browbeat
        - create_networks
        - browbeat_shaker_build
    - role: 030-browbeat-adjust-nova-allocation-ratios
      when:
        - deploy_browbeat
        - ana_enabled
    - role: 031-browbeat-collect-metadata
      when:
        - deploy_browbeat
        - browbeat_collect_metadata
    - role: 032-browbeat-install-microcode
      when:
        - deploy_browbeat
        - update_microcode
    - role: 033-browbeat-adjust-security
      when:
        - deploy_browbeat
        - as_enabled
    - role: 050-cloud-ready
      when:
        - deploy_browbeat
        - browbeat_run
    # Only on when microcode has been upodated as that initiates a reboot
    - role: 051-cinder-remount-loopback
      when:
        - deploy_browbeat
        - deploy_scenario|int not in deploy_scenarios_with_ceph
        - update_microcode
    - role: 100-browbeat-run
      when:
        - deploy_browbeat
        - browbeat_run
  post_tasks:
    - debug:
        msg: "Deployed with {{total_node_failure_count}} failures"
      when: total_node_failure_count|int > 0

    # Bugs/Thoughts
    # * Improve name ordering of tasks 000, 050, 100, 200 ... etc
    # * Improve organization of different hardware configs
    # * Handle heterogeneous hardware types
    # * Capture Memory usage?
    # * Auto install: sysstat, strace
    # * Hypervisor install for microcloud hardware (Remove beaker dependency)
    # * Robust option for introspection (Node fails introspection, remove from deploy if tolerated)
    # Speed Ups:
    # * Concurrent collectd installs (across node types)
    # * Browbeat workload vms built beforehand
    # * Shaker workload vms built beforehand
    # * Microcode pre-installed
    # Healthcheck
    #  * Get Token
    #  * Add Network
    #  * Boot Instance
    #  * Ping Instance
    #  * Delete Instance, Network
