---
#
# Rebuild playbook
#
# ansible-playbook -i "localhost," rebuild.yaml -e "foreman_url=https://foreman.example.com undercloud_hostname=undercloud.example.com foreman_user=cloud00 foreman_pass=10101 ipmi_user=quads ipmi_password=10101"
#

- hosts: localhost
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/data.yaml
    - vars/main.yaml
    - vars/main.local.yaml
  tasks:
    - name: Set Machine to rebuild
      uri:
        body: "{\"host\": {\"build\": \"1\"}}"
        body_format: json
        force_basic_auth: true
        method: PUT
        password: "{{foreman_pass}}"
        url: "{{foreman_url}}/api/hosts/{{undercloud_hostname}}"
        user: "{{foreman_user}}"
        validate_certs: false
      when: lab_hardware == "scalelab"

    - name: Rebuild Scalelab Undercloud Machine
      shell: |
        ipmitool -I lanplus -H mgmt-{{undercloud_hostname}} -U {{ipmi_user}} -P {{ipmi_password}} chassis power cycle
      when: lab_hardware == "scalelab"

    - name: Wait for Machine Rebuilding
      local_action:
        module: wait_for
        host: "{{undercloud_hostname}}"
        port: 22
        delay: 2
        timeout: 300
        state: stopped
      register: wait_for_data
