---
#
# Redeploy an Overcloud
#

# Tasks as stack user
- hosts: undercloud
  gather_facts: false
  vars_files:
    - vars/data.yaml
    - vars/main.yaml
    - vars/main.local.yaml
  remote_user: stack
  roles:
    # Add Role to check if overcloud already existing

    - role: 016-overcloud-deploy
      when: deploy_overcloud
    - role: 017-browbeat-generate-overcloud-hosts
      when: deploy_browbeat
    - role: 018-browbeat-deploy-overcloud-collectd
      when:
        - deploy_browbeat
        - deploy_overcloud_collectd
    - role: 019-browbeat-deploy-grafana-dashboards
      when:
        - deploy_browbeat
        - deploy_grafana_dashboards
    - role: 020-overcloud-disable-admin-quota
      when: disable_quota
    - role: 021-overcloud-create-keypair
      when: create_keypair
    - role: 022-overcloud-create-flavors
      when: create_flavors
    - role: 023-overcloud-upload-images
      when: upload_guest_images
    - role: 024-overcloud-create-security-group
      when: create_security_group
    - role: 025-overcloud-create-networks
      when: create_networks
    - role: 026-undercloud-route-external-traffic
      when: route_external_traffic_from_undercloud
    - role: 027-browbeat-workload-guests-config
      when:
        - create_networks
        - browbeat_workload_guests
        - deploy_browbeat
    - role: 028-browbeat-install
      when: deploy_browbeat
    - role: 029-browbeat-adjust-nova-allocation-ratios
      when:
        - deploy_browbeat
        - adjust_nova_allocation['enabled']
    - role: 030-browbeat-collect-metadata
      when:
        - deploy_browbeat
        - browbeat_collect_metadata
    - role: 031-browbeat-install-microcode
      when:
        - deploy_browbeat
        - update_microcode
    - role: 032-browbeat-adjust-security
      when:
        - deploy_browbeat
        - adjust_security['enabled']
