# 1 Controller / 6 ComputeHCIs
perf-sm5039-1-2-mm: controller-0
perf-sm5039-1-3-mm: computehci-0
perf-sm5039-1-4-mm: computehci-1
perf-sm5039-1-5-mm: computehci-2
perf-sm5039-1-6-mm: computehci-3
perf-sm5039-1-7-mm: computehci-4
perf-sm5039-1-8-mm: computehci-5
