parameter_defaults:
  ControllerSchedulerHints:
    'capabilities:node': 'controller-%index%'
  NetworkerSchedulerHints:
    'capabilities:node': 'networker-%index%'
  NovaComputeSchedulerHints:
    'capabilities:node': 'novacompute-%index%'
  BlockStorageSchedulerHints:
    'capabilities:node': 'blockstorage-%index%'
  ObjectStorageSchedulerHints:
    'capabilities:node': 'objectstorage-%index%'
  CephStorageSchedulerHints:
    'capabilities:node': 'cephstorage-%index%'
