---
#
# Deploy Overcloud
#

- name: Setup "install" tmux
  become: true
  shell: "{{tmux_install_shell}}"

- name: "Deploy Overcloud Scenario: {{deploy_scenario_human[deploy_scenario]}}"
  shell: |
    . /home/stack/stackrc
    ./home/stack/deploy{{deploy_scenario}}.sh
