---
#
# Deploy/Redeploy Overcloud
#

- name: Check if "install" tmux exists
  become: true
  shell: tmux ls | grep install
  register: tmux_install_exists
  ignore_errors: true

- name: Setup "install" tmux
  become: true
  shell: "{{tmux_install_shell}}"
  when: tmux_install_exists.failed

# ignore errors on this command as if no overcloud exists, then we can continue on
- name: (Redeploy) Check if overcloud exists
  shell: |
    . /home/stack/stackrc
    openstack stack list | grep -q overcloud
  register: overcloud_exists
  ignore_errors: true
  when: redeploy_cleanup_existing_overcloud

- name: (Redeploy) Delete existing overcloud
  shell: |
    . /home/stack/stackrc
    openstack stack delete overcloud -y
  when:
    - redeploy_cleanup_existing_overcloud
    - not overcloud_exists.failed

# Waits ~180s for stack to be cleaned up
# ignore_errors as no longer matching overcloud means stack is deleted
# Maybe inverse grep instead
- name: (Redeploy) Wait for stack delete to complete
  shell: |
    . /home/stack/stackrc
    openstack stack list | grep -q overcloud
  register: stack_still_exists
  until: stack_still_exists.rc != 0
  retries: 36
  delay: 5
  ignore_errors: true
  when:
    - redeploy_cleanup_existing_overcloud
    - not overcloud_exists.failed

# Wait 120s for the nodes to enter cleanup
- name: (Redeploy) Wait for nodes to enter cleanup
  shell: |
    . /home/stack/stackrc
    openstack baremetal node list | grep 'clean wait'
  register: nodes_start_cleanup
  until: nodes_start_cleanup.rc == 0
  retries: 24
  delay: 5
  when:
    - redeploy_cleanup_existing_overcloud
    - not overcloud_exists.failed

# Waits ~600s for nodes to no longer show cleaning status
# ignore_errors as failed means no nodes were found in clean wait|cleaning state
# Can not wait for available as we need to wait for all nodes to be available
- name: (Redeploy) Wait for nodes to finish cleanup
  shell: |
    . /home/stack/stackrc
    openstack baremetal node list | egrep 'clean wait|cleaning'
  register: nodes_still_cleaning
  until: nodes_still_cleaning.rc != 0
  retries: 60
  delay: 10
  ignore_errors: true
  when:
    - redeploy_cleanup_existing_overcloud
    - not overcloud_exists.failed

- name: "Deploy Overcloud Scenario: {{deploy_scenario_human[deploy_scenario]}}"
  shell: |
    . /home/stack/stackrc
    /home/stack/deploy{{deploy_scenario}}.sh
