---
#
# Collect Artifacts off Undercloud/Overcloud
#

- name: Get timestamp
  command: "date -u +%Y%m%d-%H%M%S"
  delegate_to: localhost
  register: current_ts

- name: Set Artifact Directory
  set_fact:
    artifact_dir: artifacts/{{version}}-deploy{{deploy_scenario}}-{{current_ts.stdout}}

- name: Ensure artifact directory exists
  file:
    path: "{{artifact_dir}}"
    state: directory
  delegate_to: localhost

- name: Collect deployment Artifacts
  synchronize:
    src: "{{log_dir}}"
    dest: "{{artifact_dir}}/deployment-log"
    mode: pull

- name: Collect Browbeat Artifacts
  synchronize:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: pull
  with_items:
    - src: /home/stack/browbeat/results/
      dest: "{{artifact_dir}}/browbeat-results"
    - src: /home/stack/browbeat/metadata/
      dest: "{{artifact_dir}}/browbeat-metadata"
    - src: /home/stack/browbeat/log/
      dest: "{{artifact_dir}}/browbeat-log"
    - src: /home/stack/browbeat/ansible/install/group_vars/all.yml
      dest: "{{artifact_dir}}/browbeat-install-vars.yml"
  when:
    - deploy_browbeat
    - browbeat_run
