---
#
# Adjust Spectre/Meltdown Security On/Off for Perf/Scale Testing
#

- name: Adjust Security
  shell: |
    cd /home/stack/browbeat/ansible
    { time ansible-playbook -i hosts browbeat/adjust-security.yml -e 'security={{as_security}}' 2>&1 | tee -a /home/stack/log/203-security-update.log ; } 2>> /home/stack/log/203-security-update.log
