---
#
# Adjust Spectre/Meltdown Security On/Off for Perf/Scale Testing
#

- name: Adjust Security Block
  block:
    - name: Adjust Security
      shell: |
        set -o pipefail
        cd /home/stack/browbeat/ansible
        { time ansible-playbook -i hosts browbeat/adjust-security.yml -e 'security={{as_security}}' 2>&1 | tee -a {{log_dir}}/203-security-update.log ; } 2>> {{log_dir}}/203-security-update.log
  always:
    - name: Collect Adjust Security Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/deployment-log"
        mode: pull
      when: collect_artifacts
