---
#
# Update microcode to protect against Spectre/Meltdown
#

- name: Update Microcode Block
  block:
    - name: Update Microcode
      shell: |
        set -o pipefail
        cd /home/stack/browbeat/ansible
        { time ansible-playbook -i hosts browbeat/adjust-microcode-rpm.yml -e 'rpm_url={{microcode_rpm}}' 2>&1 | tee -a {{log_dir}}/032-0-microcode-update.log ; } 2>> {{log_dir}}/032-0-microcode-update.log
  always:
    - name: Collect Update Microcode Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/mccloud-log"
        mode: pull
      when: collect_artifacts
