---
#
# Update microcode to protect against Spectre/Meltdown
#

- name: Update Microcode
  shell: |
    cd /home/stack/browbeat/ansible
    { time ansible-playbook -i hosts browbeat/adjust-microcode-rpm.yml -e 'rpm_url={{microcode_rpm}}' 2>&1 | tee -a {{log_dir}}/202-microcode-update.log ; } 2>> {{log_dir}}/202-microcode-update.log
