---
#
# Install Browbeat via playbook
#

- name: Install Browbeat
  shell: |
    cd /home/stack/browbeat/ansible
    { time ansible-playbook -i hosts install/browbeat.yml 2>&1 | tee -a {{log_dir}}/103-browbeat-install.log ; } 2>> {{log_dir}}/103-browbeat-install.log
