---
#
# Collect Browbeat Metadata
#

- name: Browbeat Metadata Block
  block:
    - name: Browbeat collect metadata
      shell: |
        set -o pipefail
        cd /home/stack/browbeat/ansible
        { time ansible-playbook -i hosts gather/site.yml 2>&1 | tee -a {{log_dir}}/031-0-browbeat-gather.log ; } 2>> {{log_dir}}/031-0-browbeat-gather.log
  always:
    - name: Collect Browbeat Metadata Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/mccloud-log"
        mode: pull
      when: collect_artifacts
