---
#
# Adjust Nova allocation ratios to allow greater overcommit
#

- name: Nova allocation ratios Block
  block:
    - name: Adjust Nova allocation ratios
      shell: |
        set -o pipefail
        cd /home/stack/browbeat/ansible
        { time ansible-playbook --forks 100 -i hosts browbeat/adjust-nova-allocation.yml -e "cpu_allocation_ratio={{ana_cpu_allocation_ratio}} ram_allocation_ratio={{ana_ram_allocation_ratio}} disk_allocation_ratio={{ana_disk_allocation_ratio}} restart_nova=true" 2>&1 | tee -a {{log_dir}}/030-0-adjust-nova-allocation.log ; } 2>> {{log_dir}}/030-0-adjust-nova-allocation.log
  always:
    - name: Collect Nova allocation ratios Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/mccloud-log"
        mode: pull
      when: collect_artifacts
